### ISSUE TITLE
Scrubber form values are not submitted

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#1013]
From what I can tell, the form object in Scrubber is not submitted at all, so it is just running defaults. This is obvious if you uncheck "Make Lowercase". It also explains issue #1011 and issue #1005. A fix is needed urgently.

**Comment by scottkleinman** [comment]
OK, I have found two problems. Session_manager.py, [line 151](https://github.com/WheatonCS/Lexos/blob/master/lexos/managers/session_manager.py#L151), reads `session['scrubbingoptions']['stop_words_']`. This generates an error. The problem appears to be a typo, and removing the underscore gets rid of the error message.

The more significant problem is in scrubber.py, lines [1054](https://github.com/WheatonCS/Lexos/blob/master/lexos/processors/prepare/scrubber.py#L1054) and [1062](https://github.com/WheatonCS/Lexos/blob/master/lexos/processors/prepare/scrubber.py#L1062). These two lines always call `get_remove_digits()` at the end of the scrubbing process. I've successfully tested a hack that fixes the problem:

```python
functions = [to_lower_function, consolidation_function, lemmatize_function]
if digits:
    functions.append(get_remove_digits)
functions = functions + [stop_keep_words_function, total_removal_function]
text = general_functions.apply_function_no_tags(input_string=text, functions=functions)
```
This inelegant solution preserves the order in which the functions are called, but there is probably a better way to do it. For now, it just highlights the need for conditional logic, which is missing from the current code. I am not sure if we need to make similar modifications for other scrubbing options, but it seems likely.

**Comment by mleblanc321** [comment]
just started another look ...

**Comment by mleblanc321** [comment]
@scottkleinman's "better" suggested fix:

```
# apply all the functions and exclude tag
functions=[to_lower_function,
            consolidation_function,
            lemmatize_function,
            stop_keep_words_function,
            total_removal_function]
if digits:
    functions.insert(3, get_remove_digits)
if tags:
    text = general_functions.apply_function_exclude_tags(
        input_string=text, functions=functions)
else:
    text = general_functions.apply_function_no_tags(
        input_string=text, functions=functions)

return text
```
Note that this adds some conditional logic to call `get_remove_digits()` only if Remove Digits has been selected. I am not sure if the same logic needs to be applied to the other functions. Hopefully not because, for instance, lemmatising on an empty lemma list has no effect, so the function just returns the original string. I'm not sure whether there would be an discernible advantage to bypassing the function altogether...

**Comment by mleblanc321** [comment]
a summary (so far):

(0) Session_manager.py, [line 151], reads session['scrubbingoptions']['stop_words_']. This generates an error. The problem appears to be a typo, and removing the underscore gets rid of the error message.

(1) Session_manager.py, [line 959](https://github.com/WheatonCS/Lexos/blob/4d4738a0b06584f5ac8361cf03e4a69a0b11c60a/lexos/processors/prepare/scrubber.py#L959)]: `get_remove_digits() `just should *not* be called at this point; these lines (958, 959) (if statement and call) should be commented out (as is, we just waste time calling this function; since we don't update the text string, it is a no-op):
`# -- 5. digits -----------------------------------------------------------`
**# will be applied at end if needed**
   **#** `if digits:`
       **#**  `get_remove_digits(text)`

(2) checking other scrubbing options:
`to_lower_function()`  -- i think this is fine since we `def` only the version of the function we need, so i this is ok to remain in the function list

(3) i have _**not**_ tested consolidations and lemmatization

(4) to avoid always calling for the removal of digits, @scottkleinman is correct and lines 1048-1066 can be replaced with:

```
# apply all the functions and exclude tag
functions=[to_lower_function,
            consolidation_function,
            lemmatize_function,
            stop_keep_words_function,
            total_removal_function]
if digits:
    functions.insert(3, get_remove_digits)
if tags:
    text = general_functions.apply_function_exclude_tags(
        input_string=text, functions=functions)
else:
    text = general_functions.apply_function_no_tags(
        input_string=text, functions=functions)

return text
```

**Comment by scottkleinman** [comment]
Additional bugs I have noticed:

- Consolidations works but produces results for only some instances of the pattern, and they are often wrong
- Lemmas does not work at all, as far as I can tell.
- Stopwords only works with some words
- Keepwords keeps a lot of words not in the list
- For Special Characters, mappings in the input field or from an uploaded file do not work. Early English HTML does not work.

I am currently working to identify the source(s) of these problems.

**Comment by scottkleinman** [comment]
Changes noted above have been pushed and appear to be working, so I am closing this issue.
