### ISSUE TITLE
Letters/Chunk

### ISSUE THREAD

**Issue by ShiweiJuliaHuang** [WheatonCS/Lexos#147]
I hope to change "Letter/Chunk" to "Character/Chunk" to support non-English files.

**Comment by mleblanc321** [comment]
right;  shiwei means on the labeling on the cutter tool (it wasn't clear to her that she
should only use char/chunk in chinese, as i think(??) the chunks per file assumes
we'll count white-space delimited word tokens)

**Comment by JingxianL** [comment]
I tried to change that, but the space for the button isn't enough to write character/chunk.

**Comment by mleblanc321** [comment]
i wonder how *annoyed* people will be at our use of "letters" vs. "characters"?

**Comment by scottkleinman** [comment]
Personally, I think we should use "code points".

Seriously, this needs to go in the bag of terms we need to discuss for linguistic consistency across the application. "Chunk" is also questionable. In terms of "letter" v. "character", there may be some room for ambiguity depending on the context. I'll have to look at the UI more closely before I can answer Mark's question. But I've labelled this issue a question so that we can come back to it.

**Comment by chantisnake** [comment]
I don't think people will care at all as long as they understand.

Letter/character is the most understandable, I think.

**Comment by gryphonwastler** [comment]
covered by issue #186
