### ISSUE TITLE
Upload: needs progress bar

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#150]
It'd be useful for the loader to have one of the following features: a progress bar, a visible confirmation that it has completed loading a set of files, or a tally of number of files loaded (or all the above).
     Reason: it takes a while to load a lot of files, and it's unclear when the loadiing is complete.

**Comment by scottkleinman** [comment]
This might relate to a general need for a "loading" or "working" icon for actions that don't happen immediately, such as the generation of word frequency tables.See issue #159.

**Comment by JingxianL** [comment]
I am working on adding an progress bar or a loading icon in the upload progress. I found out that there is an xhr.upload.addEventListener("progress", function(evt) that calculates the percentage of uploading completion. But that function currently is not working at all somehow, and there is also an thread in the console every time there is an upload, "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience".

**Comment by JingxianL** [comment]
I finished the upload process bar.
