### ISSUE TITLE
Cutter: issue when chunk size > file size

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#153]
For a whole day, I kept getting an "internal server error" message from Lexos when trying to chunk a few hundred files in 1,000-word segments.  I thought it was an issue at the server end.  I finally figured out that the problem was caused by a single file in my corpus that had been truncated by mistake at less than 1,000 words (a 1 Kb file).  Lexos needs some way to gracefully handle this problem so as either to override it or to report to the user what the problem is.  When processing a large corpus, problems like this are going to come up.

**Comment by scottkleinman** [comment]
I can confirm this bug. In addition, cutting a 10-word text into 11 chunks will generate the error. If I understand this correctly, the number of terms must be greater than or equal to the number of chunks or the chunk size designated by the user. I think the easiest way to deal with this would be by querying the DTM. Assuming that we have created it in a CountVector variable, we could do this upfront with `num_terms = len(CountVector.get_feature_names())`. Once the DTM is a numpy array, I think `num_terms = dtm.shape[1]` will get you the number of columns (hence terms) in the `dtm` array.

**Comment by mleblanc321** [comment]
hmm, we are not replicating this error;  more work to do here ...

**Comment by scottkleinman** [comment]
Now I'm not getting this error either. Was something tweaked in the last ten days that could have fixed it?

**Comment by Gryphonwastler** [comment]
I have not been able to replicate either of these two errors directly; however, I have discovered that the cutter behave incorrectly if the file in question does not have enough units (words,letters,lines) to make one single chunk.  When cutting up a 1000 word file into 2001 word chunks, if the threshold is set at 50% then the file is not big enough to satisfy the requirements for a single chunk and when the cutter tries to cut the file it winds up breaking the entire file up into single word chunks (some only containing whitespace).  I don't know why we cannot recreate the old error, but Mark said we should assign JingXian to this because she was already working on the cutter.  This may or may not be related to any changes she has made.

**Comment by JingxianL** [comment]
I think some of these errors might be because of some dequeing happens when the queue was empty, and also some [-1].extend happened to a list when the list is empty in the cutter file. I changed those places, so that if there is any dequeueing or extending, it will check the current status of the list of queue. Also, for Scott's old problem, changing anything in the DTM won't really help, since we won't be generating a DTM after the cutting is done. But I am not sure on why cutting 1000 words file into 2001 words chunks will behave wrong but 2000 words chunk will be fine, I will look into that.

**Comment by JingxianL** [comment]
I think I fixed the problem for cut by word, and cut by lines, but cut by character is still not right. I will keep  working on this.

**Comment by mleblanc321** [comment]
>but cut by character is still not right
on MON, i'll ask you to define more specifically what is not right;  we need to be clear about what works for English vs. non-Western languages, ASCII whitespace vs. non-western white-space, etc.

**Comment by JingxianL** [comment]
Got it fixed for this issue. Should work now.
