### ISSUE TITLE
How is Lexos positioned?  for small corpus?  large corpus?

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#155]
In general: it is unclear how Lexos is positioned as a platform for small vs. big data processing.  There probably should be a message to users about the scale for which the system is currently optimized and in the future will be intended.  (It's also unclear how Lexos is positioning itself relative to such platforms as SEASR  and SEASR's implementation in HATHI. The big issue here has to do with whether Lexos will in future allow users to store worksets and workflows.)

**Comment by scottkleinman** [comment]
I don't think we have any intention of maintaining our own corpus for public access through Lexos. The server environment at Wheaton is really good for small project and to familiarise newcomers, but it's inevitably limited by internet upload times. For local installations, I'm not sure we've ever tested the limits. Some functions are just not right for large corpora (e.g. dendrograms with thousands of texts would be unreadable).

**Comment by chantisnake** [comment]
Lexo at this point, cannot handle any large data, at all.
not only the function is pretty limited, but also the code is not fast. the rolling window is still super bad even running locally, on such a powerful machine.

**Comment by mleblanc321** [comment]
with Caleb's new local installation directions (which have been successfully used by some English students in lab), we are in a better position to test local limits;

**Comment by gryphonwastler** [comment]
I think that Lexos should not be advertised as a  large corpus app.  However, if we add in the cached session info in the downloaded zip files, it could potentially make working on PARTS of a large corpus very easy (as opposed to a program like stylo where you have to continually move files in and out of your corpus foler).  I think that lexos is currently, like I've heard Mark say in the past, an exploratory tool.  If user wants to try and use lexos for anything more than that.  They should at the very least look into installing lexos locally (maybe we could take off the filesize limit for them but give them a big BE PATIENT warning when exceeding the current 4MB limit).

**Comment by jaronson13** [comment]
Once I finish testing Lexos limits for the local install I think we can close this issue. So far I've determined that uploading more than 6000 1MB files will take too long for the file browser to handle. I'll be testing larger file sizes by removing the 4MB limit and see what the localhost can handle. Here are the timed results for uploaded 1MB files:
![screenshot from 2015-06-18 10 22 07](https://cloud.githubusercontent.com/assets/7633573/8233360/d79274ae-15a3-11e5-9434-47191ae151f0.png)

**Comment by jaronson13** [comment]
When uploading single bulk files, it seems that a local install of Lexos cannot handle more than a 2.0GB file without crashing the browser. The upload time doesn't seem to be an issue here, but an error is thrown before the filemanager object and preview can be generated. 

![screenshot from 2015-06-18 16 51 36](https://cloud.githubusercontent.com/assets/7633573/8241975/4d13a85c-15da-11e5-8be8-197a75f9ff9f.png)

This is the error that arises when you try to upload more than ~2.0GB

![screenshot from 2015-06-18 16 54 16](https://cloud.githubusercontent.com/assets/7633573/8242027/bf130fa6-15da-11e5-867d-2bece1b332bb.png)

**Comment by JingxianL** [comment]
I saw on upload page, the max is set to 1GB per file. I am little bit concern about when one file is 1GB, first, how big will the workspace be? Are we then able to upload a workspace that is more than 1GB large? Also how many 1GB files are we able to upload? And if we upload that many are we able to process all the files before any thing crashes?

**Comment by jaronson13** [comment]
Downloading a workspace with a 1GB file turns out to be smaller than the original upload, with a size of about 985MB ( Zip file compression?) . It seems like you cannot upload a workspace that is larger than 1GB, just as you cannot upload a file larger than 1GB. Uploading multiple 1GB files is not a problem, but 
handling those files and running tools such as cut and scrub on those files would take too long and probably cause crashes.

I've been working with a 1GB file this morning and I think Lexos can handle it, but every tool runs way too slowly. I tried cutting the file and I didn't have the patience to wait. I doubt many users will wait 20+ minutes just to cut a 1GB file into 5 segments. Maybe we should change the file limit to be more in the range of 200-500MB. What do you think @mleblanc321?

**Comment by mleblanc321** [comment]
this is a good thing to test;  i think constants.py is set up for a quick change (500MB? 250MB?);
talk among yourselves as to what seems to upload,scrub, and cut in reasonable times;
(remember, on server we were thinking of staying at 4M or slightly larger; 1G is for local install only
as i'm assuming we'd change constants on the server when we pull on lexos.wheatoncollege.edu)

**Comment by jaronson13** [comment]
We talked yesterday about what a reasonable limit might be for local install, and we decided that in order to use scrub/cut in decent time the limit might be 100MB. I think the 1GB limit works for the upload, but beyond that the other tools become very slow. 

Would the limit hold for individual files, or could it possibly be a total cumulative limit that prevents multiple files to surpass 100MB? ie. if you upload a 60MB file, then try to upload a 50MB one there would be a error because the cumulative size would be greater than 100MB

**Comment by scottkleinman** [comment]
This is a really good discussion. I want to add that the theoretical niche we want Lexos to fill is the analysis of smaller texts/corpora. For really large amounts of text, the command line is a better route. That said, I think a lot of people who do not have "big data", but who have larger amounts, will want to use Lexos. Although Jesse has been putting it through the stress test, I think it's reasonable to let that happen a bit in the wild as well. So we can err--*to some extent*--on the side of larger limits and see what happens.

So why not keep the limit as 1GB for upload. I presume that the scenario Jesse paints would be that the shorter files would process faster but it would appear slower to the user because Lexos would be processing multiple files. What about doing a file size detect and flashing a warning that files above 100MB can take a considerable amount of time to process. The warning could even provide a link to to tables like those Jesse posted telling the approximate processing times and when the browser is likely to crash.

**Comment by JingxianL** [comment]
I think if we keep the file size as 1GB, but if we actually upload 1GB file, then upload is all the user can do. We can't scrub or cut the file that is 1GB even on a local install. I don't think we should give the user a limit which all they can do is just to upload the file and do nothing after that.

**Comment by chantisnake** [comment]
Is this still relevant now?

**Comment by scottkleinman** [comment]
I think we'll probably have to re-address it at some point, but for this year we've decided on 250 MB. Let's close it, and we can open a new issue next year if necessary.
