### ISSUE TITLE
Tokenizer does not support unicode

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#161]
When enter Chinese file, the program gets slow and returns unreadable code. I assume is that we forget to decode.

**Comment by mleblanc321** [comment]
do you mean you uploaded a .txt file (with mandarin)
and what specifically does not work?  (remember if you use
any of the analysis tools, you must use character ngrams, not words)

m

On Sat, May 30, 2015 at 6:18 PM, Cheng Zhang <notifications@github.com>
wrote:

> When enter Chinese file, the program gets slow and returns unreadable
> code. I assume is that we forget to decode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/161>.
>



-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Meneely Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by chantisnake** [comment]
tockenizer is just created by Sarah yesterday.  here is what happend

**Comment by chantisnake** [comment]
![screenshot from 2015-05-30 15 11 46](https://cloud.githubusercontent.com/assets/10100995/7898937/84f8a322-06de-11e5-92d3-cea1603df907.png)
![screenshot from 2015-05-30 15 12 42](https://cloud.githubusercontent.com/assets/10100995/7898938/87bd7e98-06de-11e5-945c-e03d55d32e09.png)

**Comment by chantisnake** [comment]
this is obviously decoding in the wrong way. I have encountered that when I try to do analyse on Chinese webpage. and I do not know how to solve this

this happens because a Chinese Character is consist of 3 '\x' unicode, like this:
In[3]: u'一'.encode('utf-8')
Out[3]: '\xe4\xb8\x80'

and the program obviously decode 3 unicode respectively, like so:
In[9]: a = u'一'.encode('utf-8')
for item in a:
    print item
�
�
�

**Comment by mleblanc321** [comment]
hmm, i did a recent pull, but i don't sara has pushed her code yet??

fyi, here is how we handle file uploads:

        # detect (and apply) the encoding type of the file's contents
        # since chardet runs slow, initially detect (only) first 500 chars;
        # if that fails, chardet entire file for a fuller test
        try:
            encodingDetect = chardet.detect(request.data[:500]) # Detect
the encoding from the first 500 characters
            encodingType   = encodingDetect['encoding']

            fileString = request.data.decode(encodingType) # Grab the file
contents, which were encoded/decoded automatically into python's format
        except:
            encodingDetect = chardet.detect(request.data)  # :( ... ok,
detect the encoding from entire file
            encodingType   = encodingDetect['encoding']

            fileString = request.data.decode(encodingType)  # Grab the file
contents, which were encoded/decoded automatically into python's format


m

On Sat, May 30, 2015 at 7:20 PM, Cheng Zhang <notifications@github.com>
wrote:

> this is obviously decoding in the wrong way. I have encountered that when
> I try to do analyse on Chinese webpage. and I do not know how to solve this
>
> this happens because a Chinese Character is consist of 3 '\x' unicode,
> like this:
> In[3]: u'一'.encode('utf-8')
> Out[3]: '\xe4\xb8\x80'
>
> and the program obviously decode 3 unicode respectively, like so:
> In[9]: a = u'一'.encode('utf-8')
> for item in a:
> print item
> �
> �
> �
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/161#issuecomment-107077345>.
>



-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Meneely Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by akuisara** [comment]
I just pushed my latest fix to the Tokenizer. I realized that there is no problem with the file processing in any Python functions, but the [tidy-table.js](https://labs.mbrooks.info/demos/Tidy-Table/#settings) instead. In order to display a sorted table on the Tokenizer page, I was using the tidy-table.min.js used by Word Cloud. I had a look at the [tidy-table.js source code](https://github.com/nuxy/Tidy-Table/blob/master/tidy-table.js), which does not handle non-western data strings. So I did the following fix so that the table supports Unicode strings now:

###### Old JS Code
``` JavaScript
var val = vals[j][k];
```

###### New JS Code (Supports Unicode)
``` JavaScript
if (k === 0)
    var val = decodeURIComponent(escape(vals[j][k]));
else
    var val = vals[j][k];
```

###### Result of New Tidy Table
![screen shot 2015-05-31 at 6 45 03 pm](https://cloud.githubusercontent.com/assets/4997873/7904404/d8a49eac-07c6-11e5-9e3f-1b2eb31494ed.png)

As can be seen from the result, we might need to fix the scrubber, which does not scrub Chinese white spaces.

**Comment by chantisnake** [comment]
I don't think scrubber are supposed to scrub white spaces.

**Comment by mleblanc321** [comment]
excellent!  good job, sara;

small point:  let's format the output on the screen to, say, six places after the decimal point

i also think we might want to label the table with some basic stats, e.g.
total words: X    unique words:  Y

**Comment by mleblanc321** [comment]
RE: scrubbing white space (in Chinese and other non-western languages that do not
tokenize by whitespace) ... if the user selects "only within words", this should avoid any capture of character ngrams outside of "words" (or in this case, strings of characters);  again, this is something that we should mention "in the margins"

**Comment by akuisara** [comment]
Decimal point formatting is an easy fix. Currently, only the outputs on screen are formatted to 6 decimal places without modifying the original data in DTM. 

As for the basic stats, I am not sure how they should be embedded into the Tidy Table. Also, Moses mentioned it to me today, it would be really nice if the table header is fixed when scrolling down the table. Since we are using TidyTable.js to generate the table, it is possible but takes some time to incorporate more stats and also to fix the table header. 

In terms of Chinese white spaces, "only within words" does not work well. @JingxianL is currently working on it and she found that Chinese white spaces are combinations of `u'\u3000'` with `u'\n'` or `u''`.

**Comment by scottkleinman** [comment]
I'm not sure if this addresses the issue of stats, but it almost seems like "total words" and "number of unique words" can go in a <div> above the table.

Good job, Sara, on the character encoding, but keep in mind that we may want to explore alternatives to Tidy-Table, as it might not be the best fit for big data sets. I have been checking out DataTables. Here is an [example of a table with 5,000,000 rows](https://datatables.net/release-datatables/extensions/Scroller/examples/server-side_processing.html).

**Comment by akuisara** [comment]
Thank you, I really like how a loading box is showing in your example of the table with 5,000,000 entries. But for our Tokeinzer table, it crashes when the number of chunks is very large. I figured, tidy-table might not be the best way.

**Comment by scottkleinman** [comment]
If you want to experiment, [this example](https://datatables.net/release-datatables/extensions/Scroller/examples/large_js_source.html) might be easier. It accepts the whole table and does everything on the client side. The example has 50,000 rows, and it seems to work. [DataTables](http://www.datatables.net/) also allows you to fix the first column. If you had a DTM--presumably with the terms in columns--you're going to need horizontal scrolling even more than vertical scrolling.

**Comment by akuisara** [comment]
TidyTable was switched to DataTable, which runs faster and prevent the program from crashing. The old problem of Unicode encoding occurred, which is fixed now.
