### ISSUE TITLE
Cut: The Cut Set Labelling Options-Use Chunk Boundaries Doesn't work

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#177]
The default for cut set labelling options is use chunk number, but use chunk boundaries does not work at all. The options for this is also not cached.

**Comment by akuisara** [comment]
Just by looking at the code for cutter, labelling by chunk boundaries is not implemented. It shouldn't be hard to implement the function for `Words/Chunk`; it might be tricky for `Lines/Chunk` and `Chunks/File` since we need to count the total words per chunk inside the cutter function; but for `Letters/Chunk`, I don't think labelling by boundary is a good idea. However, this is exactly the opposite situation for Chinese.

**Comment by mleblanc321** [comment]
jingxian and i discussed this today; i think we should drop the chunk boundaries option (and always just use the number chunk boundaries)

**Comment by JingxianL** [comment]
Fixed.
