### ISSUE TITLE
Word Cloud check boxes

### ISSUE THREAD

**Issue by ShiweiJuliaHuang** [WheatonCS/Lexos#181]
Under "Word Cloud", "Multi Cloud", "Bubble Viz", are check boxes the most efficient way? User cannot select multiple boxes in one time though.

**Comment by scottkleinman** [comment]
I'm not sure what you are referring to here. Can you clarify what check boxes are being used?

**Comment by scottkleinman** [comment]
Do you mean this?
![capture](https://cloud.githubusercontent.com/assets/1125917/8101687/61ef2a38-0fce-11e5-9c1d-e812c623694a.JPG)
If so, I don't think the Maximum Number of Words needs to be shown with a check box. It can be displayed by default in the same row as the other options.

**Comment by ShiweiJuliaHuang** [comment]
- Would it be better if we allow users to select multiple segments rather
than one segment each time? It's under Visualize Word cloud, Multi cloud
and bubble viz.

On Thu, Jun 11, 2015 at 3:13 AM, scottkleinman <notifications@github.com>
wrote:

> Do you mean this?
> [image: capture]
> <https://cloud.githubusercontent.com/assets/1125917/8101687/61ef2a38-0fce-11e5-9c1d-e812c623694a.JPG>
> If so, I don't think the Maximum Number of Words needs to be shown with a
> check box. It can be displayed by default in the same row as the other
> options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/181#issuecomment-111019912>.
>



-- 
Best,
Shiwei

**Comment by gryphonwastler** [comment]
I changed the file selects on these pages to be consistent with the UI throughout the rest of the app.  I could certainly make it so that the max num words is always visible.  But I think the file select options are probably going to stay the way they are for 3.0 so I'm going to go ahead and close this issue for now.

**Comment by scottkleinman** [comment]
The check boxes look good to me, but it is not collapsing to a single row on load like the Select menu did. This looks a bit odd, though maybe this is just because I'm used to the other look. However, I notice that clicking Get Graph generates a "No file selected from actives" error, even though boxes are checked.

**Comment by gryphonwastler** [comment]
That's my fault.  That was working before I went to lunch!  Hmm. I will fix that.
