### ISSUE TITLE
Warning in terminal when start running lexos.py

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#196]
I got this warning in my terminal when I run the local host on my computer. 
``` 
This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
```

**Comment by JingxianL** [comment]
Also, I reset my page and realized that it is reset directly back to the upload page. Are we change that to be like this?

**Comment by chantisnake** [comment]
This is due to the use of matplotlib usage in analyze/extra.py/informatin class. I think it is fine. 

I think this is because there is no place calling that function. Let's see if that warning still exist after statistic generator is implemented.

(and programmers don't care about warning...

-----Original Message-----
