### ISSUE TITLE
should raise a warning when people are using scrub and do not check the correct option

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#223]
If the file is an old english or early english file, and they don't check the Special Characters in scrubber, we should raise an warning.

**Comment by chantisnake** [comment]
because that will make other function not work appropriately.

**Comment by scottkleinman** [comment]
This problem is caused only by HTML/XML/SGML documents which have entities. It can be addressed partially by better documentation, tooltips, and possibly changing the label of the option. But those are not full-proof solutions, so I'm recommending them on top of what Moses suggests.

Here's a possible implementation. Right now, Lexos detects the presence of angle-bracket markup tags and displays the strip tags option. Why don't we extend this function to detect common HTML entities (and practice, these are likely to be from European languages). If these are detected, Lexos can flash a message like "Your document appears to contain HTML entities. Would you like to convert them to Unicode?". If the user answers no, they are taking their chances that they will end up with "words" like "eacute" and "uuml". If they answer yes, we apply a standard rule set which converts these entities to their Unicode equivalents.

This system can't be applied to XML and SGML texts, since there are no standard entities* and no restrictions on length (making it dangerous to try to detect entities by regex). In these cases, I think that the function to detect angle brackets should provide a warning that the document may contain entities and point the user to the Special Characters option.

* Of course, XML has a few standard entities like `&amp;`, which we can detect. Some types of data may also conform to published standards. In our enormous amount of spare time, we should perhaps try to implement a rule set based on the standards of the [Medieval Unicode Font Initiative (MUFI)](http://folk.uib.no/hnooh/mufi/specs/MUFI-Alphabetic-3-0.pdf). This is a complete set of Unicode code points and equivalent entity representations for use in the markup of medieval texts. But that opens up a new set of issues, since many of the code points are for combining characters, and our current functions don't handle that.

**Comment by mleblanc321** [comment]
scrubber needs a rewrite (but not on this release); there is a thesis (undergraduate, Masters) in there somewhere .... but i wax on ...  since Scrubber is early in the pipeline, we are fragile here ... so this does deserve some attention; perhaps at least warnings?  [i've assigned caleb to this as he's looked at the matching (scrubber) code most recently; ... caleb, what are the regex we use?  we should make sure we are not being greedy, [for example, we should be using .*? (question mark needed so match will be first match, not longest)]

**Comment by scottkleinman** [comment]
As of Summer 2016, tagged texts are now handled, and the presence of entities does not seem to break any of the scrubbing functions. I agree that it would be nice to give the user a warning (and some guidance about what to do) if their texts contain entities. But that can be left for future UI work, and, in the meantime, we can document it in _In the Margins_.

**Comment by scottkleinman** [comment]
I've added this to our _In the Margins_ notes, so I'm removing the "In the Margins" label. However, the "Enhancement" label still applies, so I am leaving this issue open.

**Comment by scottkleinman** [comment]
I've folded the point about warning users that their texts have entities into issue #502, so I think we can close this issue.
