### ISSUE TITLE
Statistics page need to be changed

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#225]
1. It is not inherit the base_analyze. I know that there is problem with extend, but if you don't extend, it will be hard and inconsistent if we want to add feature to base_analyze.

2. There is a variable `lable2`, which is exactly the same as `label`, can someone explain why it exists?

3. You are not using temp label.

@austinrg7

**Comment by austinrg7** [comment]
Uhmm please leave it the way it is.  The reason we do not extend base analyze is because there is no block options for the stats page.  It's kinda hard to explain the labels and labels2 thing but I can assure you they are different by the time the post request is rendered.  A better name for labels2 might be allFiles and labels could be named selectedFfiles or something.

**Comment by austinrg7** [comment]
In terms of temp labels I had not realized that was not being applied so if you want to make that fix you can.

**Comment by chantisnake** [comment]
Sorry I did not see your reply when I push the code, I have change the front-end to extend base-analyze.

If you do not like it, just create a copy of your file and pull and replace my file with your file.

**Comment by chantisnake** [comment]
I think:
the `select a file` should be in `block option` instead of `block content`
and the `submit` button should be in `block submit`

**Comment by chantisnake** [comment]
@austinrg7 I have changed a lot on the statistic page, including caching, bug fix, and code optimization. If you are not happy with those, please talk with me, and we can change it back
