### ISSUE TITLE
zenodo.org

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#258]
http://zenodo.org/record/10956#.VctBOhNVhBc
[do we want to keep/update such a page with v2.5 ?]

do we want to keep v2.0 out there as "stable release" ?

**Comment by scottkleinman** [comment]
I spent some time on Zenodo yesterday trying to update the entry, but it appears that I don't have authorial access. Some users have found it difficult to find the download link because Zenodo displays a code preview above it. Also, the page title is 'Summer 2014', which then gets used for the title in the bibliographic citation. Also, for some authors (including myself), the username gets cited instead of the full name (this can probably be fixed by updating my profile).

In terms of the narrower question--should v.2.0 remain the stable release--I would say yes. We still have to add some tooltip documentation for new tools like Topword. More importantly, Select still behaves erratically. You can get what you want done if you reload the page, but it's quirky. We're going to need to sit down (probably during the Christmas break) and really try to solve some of the problems that come from using DataTables as an interface.

**Comment by scottkleinman** [comment]
Changing my profile on Zenodo and GitHub fails to change the username. We may have to create a new page. Who has authorial access?

**Comment by mleblanc321** [comment]
bryanJensen?   bryanawjensen@gmail.com

**Comment by scottkleinman** [comment]
It looks like it might have been set up by Clayton Rieck.

**Comment by mleblanc321** [comment]
cheng asked about this yesterday;  defining "stable" is so tricky;  for now, i'd say we just leave things as is until scottK visits in person

**Comment by scottkleinman** [comment]
I notice that @chantisnake has created a Zenodo page for v. 3.0: [https://zenodo.org/record/56751](https://zenodo.org/record/56751). I have edited it to reflect the bullet points in our release history, updated the licence, and so on. But I'm not sure if it reflects the actual release code, as I can't see how the code upload works.

@chantisnake, can you look into this?

**Comment by chantisnake** [comment]
I don't think that was I who created this... But it looks good
