### ISSUE TITLE
Lexos API

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#273]
will this be useful?

**Comment by mleblanc321** [comment]
this refers to ?

**Comment by scottkleinman** [comment]
Intrigued.

**Comment by mleblanc321** [comment]
ok, so chantisnake goes into a bar and comes out with an API;  "hey", he says, "i wanted an IPA"

**Comment by chantisnake** [comment]
I didn't quite get that joke...

**Comment by chantisnake** [comment]
Oh, I get it now... IPA is a beer

**Comment by scottkleinman** [comment]
So, although I hate IPAs, I love APIs. What is your suggestion?

**Comment by chantisnake** [comment]
well, I don't know about suggestions... is just make something like `api.lexos.com/stats` that will give people a json of all the statistics about the file that they uploaded. like this:
```js
{
{'mean of word count': 20},
{'standard diviation of word count': 1}
}
```

stuff like that...

**Comment by chantisnake** [comment]
this just came out from the top of my head...

**Comment by chantisnake** [comment]
this not only enables people to create native apps for specific platform but also enables people to programmatically access lexos a little easier (Although I am not sure how many people would want that...)

**Comment by scottkleinman** [comment]
The user would probably have to receive a url from the Lexos UI or from a Workspace download in order to access their individual session folder. In one sense, we are moving in the direction you suggest. Last year, Caleb started producing a json index of the uploaded files, which forms the basis for the cut by milestone function. We could expand that as we move forward, trying to maximise what gets stored in the json file. That way they could pull out individual items. But I'm not sure they would be able to use the API to call functions since, in our current configuration, they often return content intended for the UI. Still, I think that there are some important design principles to think about based on the idea of having an API.

**Comment by chantisnake** [comment]
This is a pretty crude idea, I think we can have some further discussion later

**Comment by chantisnake** [comment]
With everything turning into Ajax, the webpage actually becomes api.

So I don't think we need to purposefully do this any more

**Comment by scottkleinman** [comment]
In a sense you're right. An API is supposed to allow a user to design their own web interface, but that kind of user is not really our target audience. I still think there are some interesting API-inspired paths for Lexos, but there's no need to keep open a GitHub issue on it.
