### ISSUE TITLE
max file size problem?

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#277]
from RobinReid
my computational linguistics collaborator suggested online verision of the tool might truncate too long a file, and I did a quick test run to find he's correct.  The original file was 45K words; the scrubbed output was 20K (more or less).  I had a fleeting thought that the file might be too big

(and more)
I am sorry to keep emailing you about minor problems with the tool. I know there's a contact link on the site, but it won't give me an email address, just keeps trying to make me set up Microsoft 2010 startup--and I don't need another email program. I couldn't find any other contact information than people's personal emails on the "About" page.

The main thing I use Lexos for is scrubbing files (the rest of the tool's functions are too advanced for me--I have no idea of how to get any significance out of them) and the occasional visualization.

Today I discovered that a a file scrubbed in Lexos and then uploaded to TextSTAT (basic keyword frequencies and concordances) gave  completely different data than a plain .txt file (saved in Word, with the punctuation removed manually through Find/Replace command). THere was a significant disparity, not just one-two numbers difference which I've seen before when running a file through different programs.

The file is a 45,000 word file consisting of the text of an online review of Jackson's BoFA plus nearly 600 comments.

I copied the text to Word, saved it as a plain text file, scrubbed in in Lexos, and then uploaded to TextSTAT and did a Word frequency for the file, and a concordance for "tauriel."

Both the WF and concordance results showed 48 instances of "tauriel."  Since there was a good deal of controversy over the character (the topic of my project), I thought it was odd the total was so small.

So I went back to my word .txt file, ran a "Find" search which showed "tauriel" appeared 80 times in the file.

When I uploaded the .txt file (after removing punctuation), the Word Frequency and Concordance list reflected the greater number (there were some phrases such as taurielkili that were list

**Comment by scottkleinman** [comment]
Gulp! I recommend uploading a file and then downloading from the Scrub screen without performing any function. We might then identify whether the problem is in the scrubbing. The next step would be to grab the uploaded file from the tmp folder and then diff it with the original.

There is a separate point about contact for support here. I'll create a separate issue for that.

**Comment by scottkleinman** [comment]
It looks like you can't download your texts without performing some scrubbing action. There may be a case for placing a download button on the document management page (old **Select**, new **Manage**).

I tried uploading a 137,366 word document, downloading the workspace, and then diffing the original with the document in my session folder in Microsoft Word. There were no differences. An online diff checker gave me the same result. However, the original file was 752 KB, and the version in my workspace was 736 KB? What would cause that?

I subsequently uploaded both the original and the Lexos stored version to Voyant, and the word counts were identical. So I'm guessing that the problem is somewhere in the Lexos scrubbing functions.

**Comment by scottkleinman** [comment]
After further test, in ran the files through the default scrubbing options. Note that the defaults settings to remove hyphens and word-internal apostrophes will affect word counts. But the real problem seems to be ampersands. All ampersands are stripped regardless of whether or not they are entities. (I tried consolidating `&,and:and`, but that didn't work either. So this is something that we definitely need to deal with right away. It may or may not be related to the user's issue. I am not sure why it would lead to a different number of occurrences of the token "tauriel".

**Comment by scottkleinman** [comment]
Where are the results of our comparative tests of tokens counts?

Since entities are not detected automatically, users need to be aware if their texts have entities and create custom rule lists for them if one of the pre-set rule lists is not appropriate. This should be documented in _In the Margins_.

**Comment by mleblanc321** [comment]
>results of our comparative tests of tokens counts
Lexos/TestSuite/Statistics

**Comment by scottkleinman** [comment]
I have updated our _In the Margins_ notes with information about this issue.
