### ISSUE TITLE
Couple of things I think is worth doing in summer 2016

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#281]
I am just suggesting some of the idea for some thing to work on this summer.
1. more sophisticated debugging tool
   - better printing: print the data structure of an object (I prefer to do it with a debugger... but most of people here don't... I don't know why)
   - implement the dump file of the program (can be toggled)
   - profiling tool that can be toggled
   - write more console output to make determining the state of the program more easily (I am not sure this is necessary)
2. more sophisticated testing tool
   - automatic test and profiling, both test the speed on the front end and back end, and the errors on the back end. (this will be much more effective if coupled with dump file)
3. REFACTER!
   - scott says his front end is a little chunky... try to read `get_matrix`...
   - I will convert complicated method to class if necessary, if not, I will split them to little functions
   - a new top word tool is needed, we may even totally change the algorithm of that

Do you think all of this is worth implementing?

**Comment by scottkleinman** [comment]
Let's wait to move Bootstrap to master until next week, when both Mark and I are back from our travels. But it shouldn't hurt to develop with Bootstrap locally. (Note: I have done some work on Bootstrap Multicloud, which I haven't pushed, so it might be good if no one works on that immediately.)

I would say that debugging and refactoring can be done together. It might be worth starting with something very simple and implementing the toggle. Bootstrap-Lexos now has the cog icon in the top right corner, which is for settings. That way the toggle control can be placed in the UI. (However, please duplicate the icon and dialog, rather than replacing it, at this stage because right now it is demonstrating some ITM functions which I wouldn't want to lose.

Other tasks which seem reasonable to me would be working on faster code for similarity query and beginning to think about what we might do to develop TopWord.

**Comment by chantisnake** [comment]
I think debugging and logs are advanced features, therefore. I see no reason to implement that in the UI(obviously our user would not want to debug the program for us)

I am thinking of something like
Python lexos.py --debug --log

**Comment by chantisnake** [comment]
I just found out a very important thing... The Error message...
I think this is really urgent and this would require tons of work.

We need to discuss how to implement this.

**Comment by scottkleinman** [comment]
Yes, I think we need a better idea of what you have in mind--what kinds of errors would be logged, how it would be implemented, etc.

**Comment by mleblanc321** [comment]
cheng has implemented a nice set of fx's to help with debugging

import debug.log as debug
# then use
debug.show("lalala", someVariable)    # also works on requests and fileManager objects

**Comment by mleblanc321** [comment]
>a very important thing... The Error message...
I think this is really urgent and this would require tons of work.
We need to discuss how to implement this.

right;  i'll see if jordan and caren can devote some hours to this; cheng are you available for a discussion of how to do this?
m

**Comment by chantisnake** [comment]
I will be available tomorrow all day, I hope... At least afternoon 

I lost my sleep tonight.

**Comment by scottkleinman** [comment]
I think we should document how to use `debug.log` in the Backend Programming Guide and then close this issue.

**Comment by chantisnake** [comment]
okay, although I think pycharm debugger is a much better tool though.

**Comment by mleblanc321** [comment]
btw: pycharm has been great!

**Comment by chantisnake** [comment]
no longer relevant.
