### ISSUE TITLE
Scrubbing buttons 

### ISSUE THREAD

**Issue by Landaluce** [WheatonCS/Lexos#291]
The top and bottom scrubbing buttons are not aligned.
Top scrubbing buttons move under preview box when scrolling
Bottom scrubbing buttons are inside the preview box

**Comment by scottkleinman** [comment]
This is a known issue (which probably affects Cut as well). The idea is to keep the buttons in view regardless of the scroll position, but there is a bug in the implementation. I've struggled with where to place the buttons for best user experience, so the layout should at least be re-considered before the bug is fixed.

**Comment by scottkleinman** [comment]
This has been fixed.
