### ISSUE TITLE
In the Margins panel opens in small windows

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#294]
so In the marigins container is just chiilin offscreen, completely visible. If the window is squished, it pops into view without clicking the button. display needs to be made hidden until the buttoin is clicked in html.

**Comment by scottkleinman** [comment]
At present, the tab is `display: block` and is then hidden on page load. I tried to make it hidden by default, but for some reason that didn't work (I don't recall what it did). So, if you can find a way to make it work, I'm all for it.

One thing I didn't try was `visibility: hidden` instead of `display: none`. That might work.

**Comment by scottkleinman** [comment]
I'm not sure if this issue is still a problem. Needs testing.

**Comment by chantisnake** [comment]
I cannot get this error any more did you do something on this?

I think this will cause problem if the css or js taking to long to load, the In the Margin panel just wait there and stay open.

too bad javascript does not support async

**Comment by scottkleinman** [comment]
Yes, that is exactly what causes the problem. I haven't encountered it in a long while though. Perhaps one of us inadvertently changed the order of script loading and fixed the problem.

**Comment by scottkleinman** [comment]
This issue was originally about the panel opening in small windows. That still happens, but you have to go below tablet size for it to do so. I don't think it's something we need to worry about for release 3.0.
