### ISSUE TITLE
scripts_prepare.js

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#303]
This implementation is just bad. It creates lots of bugs in order to do something kind of useless. It moves some buttons if you scroll but barely any scrolling is needed anywhere and It doesn't actually improve the ui. It should just be deleted.

**Comment by scottkleinman** [comment]
See my comment on issue #291. If you can find a good place to put the buttons in the layout, we can definitely scrap the javascript that moves it when you scroll. That will indeed make things a lot simpler.

**Comment by chantisnake** [comment]
This causes some serious bugs:
  * because the button is continuously reloading, we cannot inspect element on that element.
  * if we click the button while it is reloading, the browser cannot get the click, therefore we need to click it for couple of times to get is come through
  * if you put your mouse on it, it keeps blinking

**Comment by chantisnake** [comment]
I think this is resolved, if not, reopen this.
