### ISSUE TITLE
Tokenize page doesn't work for some Chinese text

### ISSUE THREAD

**Issue by YiqingC** [WheatonCS/Lexos#329]
After upload Chinese texts, didn't do scrub, go straight  to the tokenize page,  for some texts the page doesn't give back table and no matter how you change the options and click the "Regenerate Table", there is no feedback. Tried with the text "DreamCH1" can be found in TestSuite/Experiments/Statistics/Chinese.

If done the scrubbing first, then go to the tokenize page, it does show a table with the original checked box "by Words", however whatever the options you change, if you click the "Regenerate Table", then the table just became a bunch of characters all together.

**Comment by chantisnake** [comment]
This looks like the same as
https://github.com/WheatonCS/Lexos/issues/326
bug 1

**Comment by scottkleinman** [comment]
This may once have been due to #326, bug 1, but now it seems that a different bug is responsible for a much worse problem. When a Chinese text is loaded, a table isn't even generated. And no error is given in either the Python or the browser console. This one will require some chasing.

I should note that the problem does not occur with the `BeowulfFullLines.txt` file, which contains some higher Unicode code point characters (vowels with length marks).

**Comment by scottkleinman** [comment]
I'm going to close this and open up a new issue, as the problem has narrowed to one set of Chinese files.
