### ISSUE TITLE
Scrubber UI enhancement suggestions

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#348]
So the Handle XML button should be related to remove tags somehow, because right now remove tags must be checked to scrub with the options from the handle xml modal. It will do the current default if they haven't handled the tags. So realistically the button should just be a little gear that says "Handle tags" on hover. And keep hyphens should have some similar sort of thing for whether or not you want to replace the hyphens with '' or ' '. It'd be useful to give  the users as many options as possible.
Also, since preview is always breaking, I think it could use some sort of rolling windowesque overhaul so people can see the changes/search the text without applying to make sure the settings are right. It's just a nuisance to discover you messed something up.

**Comment by scottkleinman** [comment]
I was hoping not to have to deal with this stuff until after the actual scrubbing functions for xml was implemented, but it sounds to me like the UI issues are interfering with that implementation. If this is so, we may want to back up and make the UI changes. Here are some suggestions based on your suggestions:

1. Hide the Strip Tags checkbox (for now). I believe it is set to be checked by default if tags are detected. The default for xml handling is to remove all tags, so that should have the same effect. If the user chooses not to strip some tags in the xml dialog, the strip tags setting can be switched off on the back ends. There are some further UI improvements we might make for this workflow, but that should get everything running for the moment. If you want to change the button to a gear icon, I suggest something like this. Replace:

```html
<button class="btn btn-success" type="button" data-toggle="modal" 
data-target="#xml-modal">Handle XML Tags</button>
```
with 
```html
HandleTags: <a class="btn btn-success" role="button" data-toggle="modal" 
data-target="#xml-modal"><i class="fa fa-cog fa-lg"></i></a>
```
2. The hyphen issue is harder. Right now, they are stripped by default unless you choose to keep them. I'm not sure how we can address this without adding two new check boxes and some new back end functions. An alternative way to handle this sort of situation is with Consolidations. That is, consolidate "-" with " " or "". Currently, however, I don't think it's possible to consolidate characters with spaces or lack thereof. It might be easiest to try to implement this, as it would provide extra functionality.

**Comment by evanlaferriere** [comment]
We should then put up tooltips about all this

**Comment by scottkleinman** [comment]
I think this issue has been dealt with, apart from the hyphens. I'm going to close this issue and open a new one for that.
