### ISSUE TITLE
Excel download in STATS page 

### ISSUE THREAD

**Issue by YiqingC** [WheatonCS/Lexos#363]
Do all the things on Mac:
Upload files, do scrubbing, then go to Analyze -> Statistics, Generate statistics, CLICK the Excel, got a file named Lexos.xlsx. Double click that, automatically opened with Numbers, showed up with no headers but only numbers.

![screen shot 2016-06-21 at 3 25 09 pm](https://cloud.githubusercontent.com/assets/15393424/16243261/6261af80-37c4-11e6-828c-18152b846b74.png)

Tried on other Mac and Linux, it works fine. 

It seems like there will be some problems when you want to open the .xlsx file with some version of Numbers.

**Comment by scottkleinman** [comment]
The downloaded buttons are auto-generated by DataTables; I haven't hooked them up to any functions specific to Lexos. This may be causing some of the issues. Note also that they may only download the data currently on the screen.

**Comment by chantisnake** [comment]
The xlsx file is correct though, I extracted it and see the header listed in the xml.

I think that is a problem with older version of numbers.

The latest version of numbers works fine, I think

**Comment by chantisnake** [comment]
Excel on windows can open all the file in stats with out any problems

**Comment by scottkleinman** [comment]
That's good. We can probably close this issue. I just want to add one caveat. The DataTable in Statistics is generated entirely on the client side, which means that it will be very slow for large amounts of data. I _think_ this will be all right since the table is organised by documents as rows. There are unlikely to be hundreds or thousands of them. The same is not the case for Tokenizer, which may have thousands of rows, and which therefore needs to grab sections of data at a time from the server. _That_ will require generating Excel and other downloads on the server side. But, as long as Statistics tables remain relatively small, it is much smoother to use the client-side functions built into DataTables (they seem to work very well).
