### ISSUE TITLE
MUFI 3.0/4.0 not fully working

### ISSUE THREAD

**Issue by kreddy95** [WheatonCS/Lexos#382]
### which option did I check
special characters -> MUFI 3 or MUFI 4

### which file did I use
The MUFI 3.0 and MUFI 4.0 dictionaries as .txt files
[MUFI_3_DICT.txt](https://github.com/WheatonCS/Lexos/files/332311/MUFI_3_DICT.txt)
[MUFI_4_DICT.txt](https://github.com/WheatonCS/Lexos/files/332312/MUFI_4_DICT.txt)

### what the bug looks like
For the majority of both dictionaries it works fine but for some of the entities it doesn't change to the character that it is supposed to.

### what I expect to happen
All of the entities in both dictionaries to change to the corresponding characters

### how to reproduce it
upload the dictionaries above (both the dictionaries as .txt files)
apply no other scrubbing options, only special characters -> MUFI 3 or MUFI 4 (respective to the file used)

**Comment by scottkleinman** [comment]
Does issue #365 explain this?

**Comment by kreddy95** [comment]
Not really, yes that does happen but for some of them it still just has the entity and doesnt even change it to a box or character or anything when it should after its been scrubbed. Downloading the file it can be seen better

**Comment by scottkleinman** [comment]
I'm not sure about this. the MUFI_3_DICT.txt file crashed for me, but that may be because of the way I downloaded it. MUFI_3_DICT.txt worked and showed the bug you describe. One of the entities not converted was `&aeligdotacute;`. When I ran the file through another pass, this became `ædotacute;`. My guess is that the regex is somehow detecting the string `&aelig` but not looking for the following semicolon.

Incidentally, going to Manage, right-clicking the document, and selecting "Preview Document" will show you the whole thing. It shows that the second pass is not saved.

**Comment by mleblanc321** [comment]
>My guess is that the regex is somehow detecting the string &aelig but not looking for the following semicolon.

right;  i started down that path but was pulled in another direction;  i've assigned to kristina to continue to check

**Comment by kreddy95** [comment]
not fully translating is fixed in 63c61b5382d0935c945d152d85151b50bc52283d

the problem is caused by putting elements in the dict (key is the Glyph, and value is entity), because there are multiple entities to the same Glyph, therefore when dict is constructed some of the entity is overwritten by other ones with the same Glyph.

therefore some of the entities is not translated.

**Comment by scottkleinman** [comment]
Interesting. I'll mull this over...

**Comment by chantisnake** [comment]
I think all the bug related to this is fixed.

I will close this, if there is further question, fell free to reopen
