### ISSUE TITLE
UI ordering to help user (cf RWA)

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#388]
Scott reordered the UI in Rolling Window (RWA) 1 -> 2 -> 3 etc.  (i like it and i think new users will too)

while writing up scrubber (for ITM) i want to write about topics in the order that Lexos runs them, but of course, our UI does not presently reflect this;

so, Scrubber (and other pages) would benefit in a like fasion?

**Comment by scottkleinman** [comment]
I'd have to think about whether that's possible for Scrubber, but, if not, it would be really good to write this up in ITM (maybe as its own page) and link to that prominently in the UI.

Side benefit. I know we have a rough outline in code comments, but I think having an ITM doc would be a really useful reference for developers.

**Comment by mleblanc321** [comment]
related (i hope) question:  Can you explain this alil' more fully (perhaps use Scrubber as an example; we have scrubber and scrub (the Scrub Tool);  is this an example (see below) of what you mean by two files (scrubber for the Scalar book, scrub for access from Lexos (e.g., in side panel) ) ?

_from ITM documentation:
_>When producing content for In the Margins, it is important to remember this dual use. If content is to appear separately in the Scalar book and Lexos, it is better to produce an independent node for that content, which can be accessed by either a Scalar page or an element in Lexos. Be very aware of the titles you provide for this material. Generally, the title will be re-used automatically by Lexos, whereas the reader of the Scalar book will access the content by the title of page in which it is embedded.__

**Comment by scottkleinman** [comment]
Scalar is meant to present content in a non-linear fashion, so it stores pages as nodes that can be linked to or embedded in other nodes. An example might be a page containing a video in the middle of some textual discussion. You could simply make the video part of the page node and be done, but what if you also wanted to embed the video in Lexos? For this, it would make sense to make the video its own node and then embed it separately in both your Scalar page and Lexos. Otherwise, Lexos would have to display the entire page, both text and video. Likewise, if you intend the content of a page to be displayed within Lexos, that might prompt you to write a short version and then write a longer version for reading as part of the Scalar book. My last point is about navigation within Scalar. Scalar uses the page title to construct its navigation links. That might cause you to come up with a page title that makes sense as a navigational link, but it might not make sense when taken out of that context and displayed in Lexos. Of course, down the line, we might add flags in Lexos to hide or replace the page title, but they're not there yet.

**Comment by cgnobrega** [comment]
Scalar is no longer used in v4.0 and RWA order is no longer used
