### ISSUE TITLE
ITM render template uses slug;  but what about Ajax?

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#391]
to preload the Scalar page's side-panel (book) text, we include the slug in render_template:
```
return render_template('scrub.html', previews=previews, itm='scrub', ...
```

do we need a compliment when scrubber.html is handled with Ajax call (to doScrubbing() ) ?

m

**Comment by scottkleinman** [comment]
I'm not sure if this is an ITM question. Here's a sample trigger:

```html
<a class="btn" id="bttn-cog" data-toggle="modal" data-target="#ITM-modal" data-slug="best-practices" data-type="dialog" href="#">
```

Use `data-slug` to designate the Scalar page. There are currently three options for where to output the ITM content:

1. `data-type="panel"` (the side panel)
2. `data-type="dialog"` (a Bootstrap modal)
3. `data-type="video-dialog"` (a bootstrap modal where the content is a Scalar page containing a YouTube video)
 
If this is just a question about how the back end is accessed by Ajax, it's like this:

```javascript
    $.ajax({
        type: "POST",
        url: "/doScrubbing",
        data: data,
        contentType: 'application/json;charset=UTF-8',
        cache: false,
        success: function(response) {
            // Do something with the response ...
        }
        error: function(jqXHR, textStatus, errorThrown){
            $("#error-modal .modal-body").html("Lexos could not perform the requested function.");
            $("#error-modal").modal();
            console.log("bad: " + textStatus + ": " + errorThrown);
        }
    });
```
There is  `/doScrubbing` route in `lexos.py`. There's a gotcha when you just want to download something. You have do the following in the Javascript:

```javascript
function downloadScrubbing() {
    window.location = '/downloadScrubbing'
}
```
Javascript directs the browser to the `/downloadScrubbing` route in `lexos.py`. Python initiates the download, but, since the `downloadScrubbing()` function in `lexos.py` doesn't return a function to render a template, the page is not reloaded.

**Comment by scottkleinman** [comment]
Is this issue still needed?

**Comment by scottkleinman** [comment]
I'm going to assume that this question is answered. Please re-open if you think it needs further discussion.
