### ISSUE TITLE
tokenize download buttons

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#405]
we know (scott knows) that the Tokenize Excel/CSV/TSV/PDF download files buttons do not work

now, i'm not confident i can replace the alert() with a call to a @app.route("/downloadCSV, ...)
where 
'''def downloadCSV
'''
would be in lexos.py ... (??)

**Comment by scottkleinman** [comment]
I started to do this, so make sure you've pulled the latest code. I stuck a `getTokenizerCSV()` function at the end of `lexos.py`. Note that I couldn't get it to work because it calls `utility.generateCSV()`. This function assumes an orientation and delimiter type supplied in `request.form`. But we cannot use that since we are not submitting the form. Therefore, we need to pass those values as part of a traditional ajax request. But that's as far as I got before I had to pack it in last night.

**Comment by evanlaferriere** [comment]
Before I get too far chasing this like Mark asked me, Scott, are you confident in taking care of this? You seem to have a better understanding of what's going on behind-the-scenes

**Comment by scottkleinman** [comment]
I can definitely do it, but I'm putting out lots of other fires. If you don't feel confident, you can leave it to me and concentrate on testing all the possible errors in cutter. I created seven error messages. Can you find combinations that trigger them all?

If it looks like I'm stuck on other things too long, we can then have you have a look at the download buttons.

**Comment by evanlaferriere** [comment]
So as they are, these buttons are situated in dataTable code. I can't get ajax calls to work in their individual action attributes, and because they aren't in the html, they don't have ID's or classes? And window.location sends the browser to /getTokenizerCSV which doesn't render a template. I think it'd be better to implement these buttons in the html, and have js events making ajax calls to the back end to get the data. Or does dataTables have native methods for exporting data?

**Comment by evanlaferriere** [comment]
I can't seem to get the button working through your instructions, nor my own attempts with the aid of stackOverflow.

**Comment by scottkleinman** [comment]
I just pulled a few minutes ago, so I'll look at this soon.

**Comment by scottkleinman** [comment]
I have restored the old UI elements. Now the download functions just need to be hooked up.

**Comment by scottkleinman** [comment]
The main problem now is that the back end functions assume that there is a `request.form`. It will take some time to create an ajax function that handles this.

**Comment by scottkleinman** [comment]
DataTables buttons are back. I figured out that you can hide the old download button and trigger it with the DataTables button using `$("#get-csv).click()`. Stupidly simple, but it took stepping back for a day to see it. I still have some styling to do on the buttons. Sadly, it did not occur to me that I might not have wifi access on a flight outside the continental United States. But I'm typing this looking out on the beach in Maui....

**Comment by mleblanc321** [comment]
scott:  i think there is sand in this reply ...

**Comment by scottkleinman** [comment]
I think we can close this now.
