### ISSUE TITLE
Filenames cannot contain non-ASCII character names

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#407]
while testing the use of **Temporary File Labels** (on Tokenize and analysis tools), we noticed that matplot lib (hierarchial clustering and PCA in k-means) crashes if the user sets non-ASCII labels (or the default filenames populate the fields with non-ASCII chars)

### which option did I check

upload file with Greek (or Spanish or Chinese or ...) characters in the filename

### what the bug looks like
matplot lib crashes
```
File "/home/lexos/Desktop/Lexos/managers/utility.py", line 441, in generateDendrogram
dendrogram(Z, orientation=orientation, leaf_rotation=LEAF_ROTATION_DEGREE, labels=tempLabels)
File "/home/lexos/anaconda2/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 2304, in dendrogram
above_threshold_color=above_threshold_color)
File "/home/lexos/anaconda2/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 1822, in _plot_dendrogram
ax.set_xticklabels(ivl, rotation=leaf_rot, size=leaf_font)
File "/home/lexos/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2914, in set_xticklabels
minor=minor, **kwargs)
File "/home/lexos/anaconda2/lib/python2.7/site-packages/matplotlib/axis.py", line 1573, in set_ticklabels
tick.label1.set_text(tick_label)
File "/home/lexos/anaconda2/lib/python2.7/site-packages/matplotlib/text.py", line 1206, in set_text
self._text = '%s' % (s,)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)
```
To do:
* we tell users (in ITM) to use ASCII filenames (the text inside the files of course can be Unicode)

* do we want to WARN the user that their filenames contain non-ASCII characters (at this early stage); even prevent them from doing it?

**Comment by chantisnake** [comment]
we can replace none ascii characters with ?

But if all the file name is none ASCII, then there is a problem...

**Comment by mleblanc321** [comment]
'''
# thinking out loud
newName = ascii_fy(oldName)
if (newName == ""):
   newName = "Missing Name" + str(id_number)
'''

**Comment by chantisnake** [comment]
That make sense.

I will fix this.

**Comment by chantisnake** [comment]
http://matplotlib.org/examples/text_labels_and_annotations/unicode_demo.html

here is a fix for Unicode.

you just need to import python3 Unicode in by

``` python
from __future__ import unicode_literals
``` 

I suggest to import this locally on the function.

**Comment by mleblanc321** [comment]
ok, python demands
```from __future__ import unicode_literals```
be at the top of the file

but ... dang, matplot lib still grumbling
```
File "/home/lexos/anaconda2/lib/python2.7/site-packages/matplotlib/text.py", line 1206, in set_text
self._text = '%s' % (s,)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 2: ordinal not in range(128)
```

hmm, gotta go ... but the example [here](from __future__ import unicode_literals) does not have unicode on the plot TICKs (on axes); hmmm...

**Comment by chantisnake** [comment]
I will look into it.

**Comment by chantisnake** [comment]
I don't really understand... why is all the code in `utility.py` now, we have a dengrogrammer in processers...

why do we need to copy all the code out instead of just changing the dendrogrammer....

importing future is utility.py is definitely dangerous, I am afraid if we don't have time to migrate cluster code to where is belongs, we can only trap that on the front end.

**Comment by chantisnake** [comment]
(all the comment below happens if `getdendro` in `request.form`)

and why is dendrogram still uses it's countvectorizer.... and the regex is out dated there.

also why do it has tons of code from `getmatrixoption()` and then do a `getmatrixoption` to overwrite nearly all the option you just get from the copied code of `getmatrixoption()`

also this code does not support all the analyze feature including propotional count and culling and tf-idf and stuff.

I will not be able to fix this bug.

**Comment by mleblanc321** [comment]
hmm, i had not reviewed that code for some time;  if time today, i'll walkthrough with alvaro

**Comment by mleblanc321** [comment]
>importing future is utility.py is definitely dangerous
why?

**Comment by chantisnake** [comment]
future affacts the whole file, that is changing the behavior of certain aspect to python3.

For example Unicode_literal will change all the string in utility.py to python3 (Unicode bytes)

That may cause problem (because we assume non Unicode string in utility.py, we need to do decode and encode on them, if we change to python3 I am not sure we need to do encode anymore.)

**Comment by chantisnake** [comment]
That is also way future package has two underscore in front of it.

That means do not use it, unless you have a super good reason for it.

**Comment by mleblanc321** [comment]
we think this works
