### ISSUE TITLE
Active Docs in Manage Doesn't Match Other Pages

### ISSUE THREAD

**Issue by cmccarthy41899** [WheatonCS/Lexos#409]
After uploading more than ten files or cutting to more than ten segments if all documents are unselected and then a document after the tenth in the data table is selected and you go to any page in prepare, analyse, or visualize it will display, usually two, different files that were not selected.

* upload more than ten files
* deselect all
* select one doc after number 10
* go to i.e. cut

**Comment by chantisnake** [comment]
Interesting...

**Comment by mleblanc321** [comment]
this is tough ....

**Comment by chantisnake** [comment]
I wonder if these is a manage page bug though, did you select the document using manage?

**Comment by evanlaferriere** [comment]
I wonder if it has to do with how dataTables paginates? I noticed if you don't have any pages active on the current pages, you cannot choose to deselect all even if you have active documents. 
Also, do we want to have y-scrolling on the manage table page? If you have more than 5 showing, instead of showing the whole table, it has you scroll through it in it's own small scroll instead of the page scroll, and I think the table is too small for people to want that feature.

**Comment by cmccarthy41899** [comment]
Yes, they are being selected on the manage page. I noticed that deselect problem as well.

**Comment by scottkleinman** [comment]
I'm pretty sure this _is_ a DataTables thing. Some response to user behaviour is querying what is in the current table in the DOM rather than seeking the information from the server. Either that or the DOM is not being updated after the server responds. I'll look at this later today (once I'm fully awake).

**Comment by cmccarthy41899** [comment]
fixed in b845b2f285fceb6b2fa02cd9831966151acf3db4

because `filemanager.enableFiles()` and `filemanager.disableFiles()`want a list, but in function `disableRow()` and `enableRow()` passed in a string to those two functions.

so in `enableFiles()` they are regarding char in string as different files 

For example if you select file 12, it will enable file 1 and file 2.
