### ISSUE TITLE
CSV is not currently working on the tokenize page

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#413]
@scottkleinman 

Steve and I are working on this. I see that we have a page already setup on `lexos.py`: `getTokenizerCSV`

But we need to create an ajax request to post that page when people click csv or tsv.

How exactly to do that?

**Comment by scottkleinman** [comment]
I'm not exactly sure. The easiest way to do this is with the `window.location = '/getTokenizerCSV';` in line 82 of `tokenizer.html`. This calls `getTokenizerCSV` in `lexos.py`. However, that function in turn calls `utility.generateCSV(fileManager)`, which requires values from `request.form`. But, since the form is not being submitted, nothing is there. I tried to simply setting strings for the these values, but I get a Bad Request error when I test. There must be something else that `utility.generateCSV(fileManager)` needs, which I am not seeing. If you can figure that out it should work.

Alternatively, we may have to create a full ajax request, sending all the form data as a json string. The function `getTenRows()` in `tokenizer.html` should be a good model. Note that it starts by calling `jsonifyForm()` (also in `tokenizer.html`), which serialises all the form values as a json object.

**Comment by mleblanc321** [comment]
perhaps go with scott's earlier (for now) suggestion that we just return to the old Download Matrix button (from v2.5);  this worked, we really need it, and we can change later when we figure this out?

**Comment by chantisnake** [comment]
that is a resonable idea, let's do it tomorrow

**Comment by chantisnake** [comment]
the download csv works now... I think... without intensive test. I sat on a bench in prudential center, fixing Unicode bug for all afternoon T_T

and it is finally working = =

fixed in the following commit(from the commit message you can see me gradually breaks down):
c60ff4822dc8c56b7a80ba1200b199d14795f706
ca8e831a4619c405a9ae641961bc1028f014505a
b23fb94d6b4a933688f8bd03f0f85aee0bf3904e
05346670d303ab39b62cef299eae4e7b7a4fe29d
08e4721445160174ac4936874ba5493c2f06850e

**Comment by mleblanc321** [comment]
oh, excellent;  your work on a bench at the Prudential Center has reached me on a porch in Poland Spring, Maine at sunrise;  a nice note to start my day;  thanks, cheng

**Comment by scottkleinman** [comment]
And, for the record, I've written up your solution in the Developer's Guide (which I've also fully updated to reflect the state of Lexos 3.0). At some point over the summer I'll merge this with the Backend Programming Guide.

**Comment by chantisnake** [comment]
yes, this solution is not pretty, But I think I have encounter some useful tip in handling Unicode when I was wondering around the web:

> encode when you have to, decode once you get data, puts `u` in front of every string you define.
