### ISSUE TITLE
Manage: select/deselect [green/off] does not work

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#453]
we seem to have lost the [green] highlighting of active files on the Manage page (?)

that is,  if i upload two files, Deselect does not turn them to Green;  it also appears that all the files stay active

**Comment by mleblanc321** [comment]
wtf?  also, the XML editing modal doesn't work ???

**Comment by scottkleinman** [comment]
Separate problems. I think there was a typo in the DataTables CDN call, but I've fixed it.

I've also fixed the "Set All" button. That one's worth noting. The click event was being detected with `$("#set-tags-button").click(function(event) { ... });`. However, since the `set-tags-button` button is being created dynamically when the modal is opened, it doesn't exist when the page is loaded. To get around this, you need to use `$(document).on("click", "#set-tags-button", function(event) { ... });`. I'm going to add this to the Developer's Guide.
