### ISSUE TITLE
move the install guide, dev docs and user guide to wiki page

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#489]
This will make our project even cleaner and more organized.

Here is a video discussing wiki page: https://www.youtube.com/watch?v=4B0XNThjO0E

**Comment by chantisnake** [comment]
Also, I don't know much about English folk, but do they want all the pdfs and docx or just a simple web page for the guides?

**Comment by scottkleinman** [comment]
I think it's reasonable to move the dev docs to the wiki. Anyone contributing to the code will be able to clone it if they want. However, I think the installation guides should remain in the main repo (or at least copies of them) so that anyone cloning it has copies on their local machine.

The installation guides have a complicated workflow. We often edit them in `.docx` and then convert to `.pdf`, which is I think what users need. But we also need a Markdown copy to display in GitHub (either in the main repo or in the wiki).

The ITM docs are development docs--drafts to go into Scalar. Technically, they should go in a separate repo, but we didn't do that last summer because we already had too much to juggle. I think we should consider it as part of the next stage of code cleanup.

**Comment by chantisnake** [comment]
pdf, docx, and markdown can be converted to each other easily with pandoc, so that is not a problem.

**Comment by scottkleinman** [comment]
I *love* pandoc and used it to produce the current documents. But, if I recall, there's an added step for converting from Markdown to `.docx`, or vice versa, which caused me some minor headaches. But nothing too bad.

**Comment by chantisnake** [comment]
fixed in #538
