### ISSUE TITLE
Browser detection

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#520]
Our Windows users are more and more likely to use IE/Edge, and our Mac users Safari. It would be nice if we could support these browsers, but our limited resources prevents it. So it may be worthwhile to use some basic browser detection to provide a warning if the user is not using Chrome or Firefox (or is using a mobile OS for that matter). I have a short Javascript that does the trick, but how and where to provide the warning is a little tricky.

Down the line, it might be worthwhile to enhance our browser support using [Modernizr](https://modernizr.com/).

**Comment by mathewleblanc** [comment]
@scottkleinman do you still have the Javascript you mentioned? If not I believe I have a script that can detect the user's browser, but like you said, we must choose a good place and manner to display the warning. Perhaps we can do something similar to @danny98m in issue #730. If we want the warning to appear only once, we may want to also use web storage and display it when the user reaches the upload page. If we want to display it every time then we won't have to use web storage or any such tracker.

**Comment by scottkleinman** [comment]
I think something like this should do the trick:

```javascript
function BrowserDetection() {
    //Check if browser is IE
    if (navigator.userAgent.search("MSIE") & > = 0) {
        // show warning
    }
    //Check if browser is Chrome
    else if (navigator.userAgent.search("Chrome") > = 0) {
        // pass
    }
    //Check if browser is Firefox 
    else if (navigator.userAgent.search("Firefox") & > = 0) {
        // pass
    }
    //Check if browser is Safari
    else if (navigator.userAgent.search("Safari") &> = 0 && navigator.userAgent.search("Chrome") & < 0) {
        // show warning
    }
    //Check if browser is Opera
    else if (navigator.userAgent.search("Opera") & > = 0) {
        // show warning
    }
}
```

**Comment by mathewleblanc** [comment]
Thank you, that will be very useful. Should we use local or session storage to know when to display the warning? Local storage will be much less invasive as after the first time the user reaches the upload page the warning will never be displayed again unless they clear their history/cache. However, session storage might be nice because it will let them know that they are using an unsupported browser every time they start a new session. This would be good in case the user forgets that their browser is not supported. I am more in favor of session storage but I am not sure if this might be so frequent that it may annoy the user.

**Comment by mleblanc321** [comment]
session storage seems to be the right choice (?) for this, since using an unsupported browser should be shared (here, on each reset)

**Comment by chantisnake** [comment]
I believe there will be an npm package for this. Please don't reinvent the wheel.

**Comment by Myles-Trevino** [comment]
The frontend has been rewritten in 4.0 and appears to work on all modern browsers.
