### ISSUE TITLE
Wrong file downloaded after file preparation on Lexos3 server

### ISSUE THREAD

**Issue by Shi26** [WheatonCS/Lexos#641]
After scrubbed one file and downloaded to computer, I reset the session and want to scrub another one. But after this time of applying scrubbing, I can only download the previous scrubbed file.

The same thing can also reproduce on cutting, which get the same result.
And even if I don't upload any file after resetting the session, I can still get the previous scrubbed and cut file.
The two files are distinct from both name and content, and I reproduce this bug on remote server from both linux and windows box.

**Comment by Shi26** [comment]
As I continue testing,
the server once downloaded the right file after apply cutting on the server, but the downloaded file has not been cut as it showed on the webpage.
And if I first go to cutter and then go to scrubber, I can get the right file from scrubber but the downloaded file also has not been scrubbed as it showed on the webpage.

**Comment by arialfie759** [comment]
I also came across this bug. For Linux I have the same issue, oddly enough I am getting no errors on my Windows and my Mac is doing some strange things. At first it would not let me access my download since an Error 1 - Operation not permitted error would occur when I tried to extract the zip folder. Then it worked just fine, but the third time I tried it wouldn't even download any scrubbed or cut text.
