### ISSUE TITLE
jQuery 2.4.4 security vulnerabilities

### ISSUE THREAD

**Issue by scottkleinman** [WheatonCS/Lexos#681]
jQuery should be updated to v3.0.0 to avoid security vulnerabilities described [here](https://snyk.io/test/npm/jquery/2.2.4?severity=high&severity=medium&severity=low). In the past, certain Lexos features have not worked with jQuery 3.0.0. I am not sure if this is still a problem (issues would only be detectable with extensive testing). The link provided gives some simple remedies which would be easier to fix before upgrading the jQuery version.

**Comment by chantisnake** [comment]
in 3.0.0 the `complete`, `error` and `success` callback is removed, and I am pretty sure we might be using it in some of our functionality.

**Comment by scottkleinman** [comment]
Removed or deprecated? If it is removed completely, that may be responsible for the errors I encountered in earlier tests. I wish I had noted at the time where these issues occurred. But this is a start.

**Comment by scottkleinman** [comment]
A quick test shows that `complete`, `error`, and `success` do in fact work with the latest version of jQuery. They should probably still be changed in Lexos, but they are probably not responsible for any Lexos functions failing with jQuery 3.x.

**Comment by chantisnake** [comment]
I suggest create a branch and change jquery to 3.0.0 right now.

**Comment by mleblanc321** [comment]
@mathewleblanc and @danny98m, after talking with @Weiqi97  -- will you do this (i believe matt has  finished a trial)

**Comment by mathewleblanc** [comment]
I looked up how to upgrade to jQuery 3.x [here](https://jquery.com/upgrade-guide/3.0/#browser-support).
It seems that we must add `<script src="https://code.jquery.com/jquery-3.0.0.js"></script>
<script src="https://code.jquery.com/jquery-migrate-3.0.1.js"></script>` to each page in order to upgrade. The first script is the new version of jQuery and the second is a plugin that identifies compatibility issues via the browser console. One of the main problems so far is that `.click(function(){})` has been deprecated in 3.x. We must now use `.on('click', function(){})` instead. So far I am not aware of any other errors except for `.tooltip()` and `.popover()` in scripts_base.js. How should I proceed? I have been changing the click functions as I go, should I continue to do this? I do not yet know how this will impact the Ajax.

**Comment by scottkleinman** [comment]
Wow! I didn't know that _that_ syntax was deprecated. It won't actually break anything since it's only deprecated, but we might want to start making the changes (even though it may not be implemented by all of our third party libraries). Perhaps create a jQuery section in the wiki [here](https://github.com/WheatonCS/Lexos/wiki/Front-End-Developer%27s-Guide) to document these considerations.

**Comment by chantisnake** [comment]
Mathew, I don't see the deprecation notice of `.click` function. I would be very surprised, and even maybe angry if they deprecate `.click` in favor of `.on('click')`, since the latter one is not type safe and the former one is.

I agree that changing both changing all the CDN versions is a pain. I will try to figure out a way so that they can be updated with our `package.json`.

**Comment by chantisnake** [comment]
Scott. I think we talked about remove all cdn packages and only use npm packages. Do you think now is a good time for that?

Also I don't think we need jQuery-migrate, since our main task this year is just to migrate to jQuery 3. I think we get plenty of time to make all the changes we need to migrate to jQuery 3.

**Comment by mleblanc321** [comment]
talking with @Weiqi97 about this;  very few folks are installing locally, so asking them to include the npm install step is not asking too much;   we want (and are) using npm as we develop code, so why not just assume npm step has been done?

**Comment by scottkleinman** [comment]
I missed @chantisnake's query from 10 days ago but have just seen @mleblanc321's reply. I'll think through the implications and see if I have any feedback later today...

**Comment by scottkleinman** [comment]
OK, I think it is worth it to have local users install `npm`. When this is implemented, we should take the current `LOCAL_MODE` code out. There are settings in the configuration, in the back end handling, and possibly in the front end.

**Comment by Weiqi97** [comment]
In #725 #753, we updated ```JQuery``` in both ```package.json``` and ```pacakge-lock.json```. The warning is gone now.

**Comment by chantisnake** [comment]
Nice job.
