### ISSUE TITLE
Multicloud upload not rendering

### ISSUE THREAD

**Issue by SeaCelo** [WheatonCS/Lexos#830]
### which option did I check
Visualize - Multicloud 

### which file did I use
mallet file
### what the bug looks like
The option to upload the mallet file flashes and disappears. 

### what I expect to happen
Option to upload mallet file.

### how to reproduce it
Try to upload mallet file in multicloud
Note, disabling styles on the browser shows the option. But uploading still doesn't work. Possible css issue?

**Comment by scottkleinman** [comment]
The multicloud "topic clouds" feature for Mallet data has been disabled in version 3.2 of Lexos (hopefully, it will be restored in the next release). If you were trying to produce topic clouds, you will have to download and install [v3.1.1](https://github.com/WheatonCS/Lexos/releases/tag/v3.1.1).

That said, the option to upload a Mallet file should not appear at all. So that probably is a css issue. Thanks.
