### ISSUE TITLE
Cutter: add zero to labels

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#838]
When creating segments in Cutter, name the files with leading zeros so that they are more easily sortable.

**Comment by chantisnake** [comment]
I think each element have a parent tag, we can create a helper called `parent_first_sort` to make sure that parent is sorted on top of the child.

This method might be less hacky, but we need to make sure that all the programmer remember to use `parent_first_sort` instead of sort.

**Comment by jacksonjreed** [comment]
having trouble figuring out what the problem is--
right now sorting after cut seems to work properly and relatively fast for 100+ segments
do you mean "more easily sortable" in the user's file system, after downloading the files?
(if so should we only add the leading zeroes when downloading the files, or maybe make it an option? some OS's sort properly without them)
or are you looking to make the sort in lexos more efficient by making the numbering alphabetical?

**Comment by scottkleinman** [comment]
This was a user suggestion. He was referring to the segments after download, which he was trying to sort in Excel. So your suggestion of adding the leading zeroes for file downloads is probably the best solution.

**Comment by chantisnake** [comment]
Okay, so it is probably more fitting to add this functionality to download instead of cutter?

When download, give a option to add 0 in front of all the parent file?

**Comment by chantisnake** [comment]
We can add a function to sort all the file in a tree, and the add 0 in front of them from top down?

**Comment by jacksonjreed** [comment]
the tree would be to determine how many 0s? that seems like a good way to do it

**Comment by chantisnake** [comment]
Yes, that is what I mean.

In fact, adding 0 when cut can be flawed, consider the following documents
```
doc -- doc_1
    \
     - doc_2 -- doc_2_1
             \
              - doc_2_2
```
where:
- `doc` is the parent of `doc_1` and `doc_2`
- `doc_2` is the parent of `doc_2_1` and `doc_2_2`

if you add 0 when cut, we will end up with the following:
- after cutting `doc`, we have `0doc` (renamed from `doc`), `doc_1`, `doc_2`
- after cutting `doc_2`, we have `0doc_2` (renamed from `doc_2`), `doc_2_1`, `doc_2_2`
then we have the following file (sorted):
```
0doc
0doc_2
doc_1
doc_2_1
doc_2_2
```
which is not desired, since the parenting relation of `0doc` and `0doc_2` is not reflected.

However, if we form a docuement tree and add label top down, it will be much simpler:
- root will have the same number of leading 0 as the height of the tree 
- for each node directly under the root, we recursively remove a 0 in the front.
In our example:
- root is `doc`, and height of the tree is `2`, then `doc` will be renamed to `00doc`
- moving down one, we have `doc_1` and `doc_2`, they will be renamed to  `0doc_1` and `0doc_2`
- the leaf `doc_2_1` and `doc_2_2` will not be renamed, since they need no 0 in the front.

**Comment by jacksonjreed** [comment]
I think I understand, but I had a different understanding of the request; I thought we were looking to add the 0s before the numbers, ie:

doc_01
doc_02
doc_03
doc_04
doc_05
doc_06
doc_07
doc_08
doc_09
doc_10
doc_11

vs. the current behavior:

doc_1
doc_10
doc_11
doc_2
doc_3
doc_4
doc_5
doc_6
doc_7
doc_8
doc_9

**Comment by chantisnake** [comment]
Uh... Sorry I misunderstood.

That is easy then. Create a helper function called `zero_filled_range` which behaves like range, but return a list of string:

```
>>> zero_filled_range(10)
["01", "02", "03", "04", "05", "06", "07", "08", "09"]
```

**Comment by chantisnake** [comment]
Here is a code snippet you might find helpful:
```python
def zero_filled_range (stop: int) -> List[str] : 
    last_elem = ending - 1

    # this is the string length of each element needs to be
    # this is equal to the number of digits in the last element
    len_of_elem = len(str(last_elem))
    def fill_zero(num: int) -> str:
        num_str = str(num)
        len_num = len(num_str)

        # add (len_of_elem - len_num) number of 0 in front of num str
        return "0" * (len_of_elem - len_num) + num_str
   return [fill_zero(num) for num in range(stop)]

# this is the label of the file that cut produces
# the orig_doc_label is the label of the parent file
# cut_num is the number of cutted documents that is needed.
cut_labels = [f"{orig_doc_label}_{num_id}" for num_id in range(cut_num)]
```

**Comment by jacksonjreed** [comment]
ok, thanks for your help! I think I can work with that.

**Comment by chantisnake** [comment]
Remember to add plenty of documentation along the way.
Also, it is required to document every function that you write.

**Comment by jacksonjreed** [comment]
I've pushed two branches that address this issue, cutter_zeroes and cutter_zeroes_b. whoever is invested in this issue, could you check out both branches and let me know which one is preferable?
cutter_zeroes modifies the cutter function to name the files internally with the leading 0s; whereas cutter_zeroes_b adds a new function to file_manager that will zip up the files, adding the 0s to the filenames in the process, when you click "Download Cut Files", while the numbering in the browser is left as it was before.
we could also add something like an option checkbox to either one if necessary.

**Comment by chantisnake** [comment]
Wanna create two pr? That will make review bit easier.

**Comment by jacksonjreed** [comment]
will do!

**Comment by scottkleinman** [comment]
I think I would favour the first option (if I correctly understand what is going). That way tools like Manager can effectively sort the newly-created segments.

**Comment by chantisnake** [comment]
I strongly prefer the first one.
the leading 0s should not just in the download. And I cannot think of anyway it will get messed up when it is not just in download.
Just adding zeros in download will make the behavior confusing for the user, since the download filename is not consistent with what they see on the web.

I think the log10 method is very innovative, but that requires working with floating point, that can maybe cause trouble in rare cases.
I would prefer just using the length of the string.

**Comment by jacksonjreed** [comment]
ok, I'll rework the first one a little!

**Comment by jacksonjreed** [comment]
oh, I remember why I did it this way--when putting the filenames together you don't know yet what the length of the longest one will be. I could let it do the numbering as it previously did, and then have a another loop to alter the filenames by adding in the 0s in the right spot, but that seems more complicated and slower.

**Comment by jacksonjreed** [comment]
I think I might see how to fix it though
