### ISSUE TITLE
accessibility issues

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#849]
celeste noted some accessibility issues that we might address (celeste -- please add in more detail here)

(1) if a user is not using a mouse (TAB to get to next button, for instance) we do not consistently use a consistent focus state (e.g., change of color on the Reset button is good)

(2) our hot-links should not be only mouse-over (need more here)

**Comment by cgnobrega** [comment]
#### Accessibility in the Lexos GUI
* See [this article](https://medium.com/salesforce-ux/7-things-every-designer-needs-to-know-about-accessibility-64f105f0881b) for general web design accessibility tips
* Tabbing over the page, several buttons are either **inaccessible** or have **no focus state** when tabbed over or moused over (e.g. No focus states- the gear icon, download workspace button. Inaccessable-browse button, In the Margins, option list buttons, and checkboxes...)
* **All forms should be initialized with a prompt and have a focus state**. Most forms in Lexos have a green halo (the focus state) when selected, but not all have a correctly initialized prompt. Visualize > Rolling Windows > Steps 3 & 4 have required fields and this is not indicated by a prompt until the user attempts to generate a graph without input when they get an error message, but the required fields still do not have any kind of indication that they need to be filled out.
* Mouseover is a big issue, not only for users who use dictation software to navigate webpages, but also anyone who struggles with mouseover. Dictation software can only detect clickable links. All the menus on Lexos are activated by mouseover, so they are undetectable to these users. Additionally, if your average user clicked these menus, they disappear meaning the user must hover to access them. The team suggests **menus be made "click-to-open" rather than "mouseover-to-open" **

**Comment by scottkleinman** [comment]
Most of the above discussion refers to v3.2; however, there are some accessibility issues in v4.0. I am testing with the [Wave Web Accessibility Evaluation Tool](https://wave.webaim.org/) and gradually fixing the most crucial accessibility problems. I think we can go through one wave of corrections (no pun intended) and then close this issue, even though this will be an ongoing task as we create new features.

**Comment by scottkleinman** [comment]
This issue has been superseded by issue #1098.
