### ISSUE TITLE
Manage: make default to show ALL files

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#850]
I find i rarely have 5 or fewer files and need to see more, often "all"

Can we make "All" the default?

**Comment by scottkleinman** [comment]
Won't that potentially make for some very long tables? It might be better to make 25 or 50 the default.

**Comment by chantisnake** [comment]
I am afraid in real world usage (where lots of cutting happening), displaying all the file can easily freeze the webpage

**Comment by jacksonjreed** [comment]
looked into this a little--
- first of all, the tables seems to load completely, *before* limiting the view to 5 documents, so currently the smaller view does not save any time loading the page.
- with ~10000 files the manage page loaded in a few seconds (on this machine), and expanding the table view took ~1 second. with ~20000 files, the page froze up while loading.

in any case, the impact seems minimal except in extreme cases, and in those cases the impact wouldn't actually be mitigated by differences in this setting
because the table occupies a window and scrolls when it exceeds that space, it seems like there isn't really an impact on useability of the interface either; so I would be in support of changing the default

**Comment by chantisnake** [comment]
This actually would make sense, since in manage, we are not sending huge data like dtm or the content of the file.
They would not need that much bandwidth and processing power.

**Comment by jacksonjreed** [comment]
changed this and made a pull request, unless there are objections?
